spring:
  application:
    name: scheduler

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/scheduler}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refreshExpiration: 604800000

logging:
  file:
    path: logs
    name: logs/scheduler.log

  level:
    root: INFO
    com.thakur.scheduler: DEBUG